"""paypalserversdk.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from paypalserversdk.api_helper import APIHelper
from paypalserversdk.models.error_details_1 import (
    ErrorDetails1,
)
from paypalserversdk.models.error_link_description import (
    ErrorLinkDescription,
)


class Error1(object):
    """Implementation of the 'Error1' model.

    The error details.

    Attributes:
        name (str): The human-readable, unique name of the error.
        message (str): The message that describes the error.
        debug_id (str): The PayPal internal ID. Used for correlation purposes.
        details (List[ErrorDetails1]): An array of additional details about the error.
        links (List[ErrorLinkDescription]): An array of request-related [HATEOAS
            links](/api/rest/responses/#hateoas-links).

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "name": "name",
        "message": "message",
        "debug_id": "debug_id",
        "details": "details",
        "links": "links",
    }

    _optionals = [
        "details",
        "links",
    ]

    def __init__(
        self,
        name=None,
        message=None,
        debug_id=None,
        details=APIHelper.SKIP,
        links=APIHelper.SKIP):
        """Initialize a Error1 instance."""
        # Initialize members of the class
        self.name = name
        self.message = message
        self.debug_id = debug_id
        if details is not APIHelper.SKIP:
            self.details = details
        if links is not APIHelper.SKIP:
            self.links = links

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        name =\
            dictionary.get("name")\
            if dictionary.get("name")\
                else None
        message =\
            dictionary.get("message")\
            if dictionary.get("message")\
                else None
        debug_id =\
            dictionary.get("debug_id")\
            if dictionary.get("debug_id")\
                else None
        details = None
        if dictionary.get("details") is not None:
            details = [
                ErrorDetails1.from_dictionary(x)
                    for x in dictionary.get("details")
            ]
        else:
            details = APIHelper.SKIP
        links = None
        if dictionary.get("links") is not None:
            links = [
                ErrorLinkDescription.from_dictionary(x)
                    for x in dictionary.get("links")
            ]
        else:
            links = APIHelper.SKIP

        # Return an object of this model
        return cls(name,
                   message,
                   debug_id,
                   details,
                   links)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _name=self.name
        _message=self.message
        _debug_id=self.debug_id
        _details=(
            self.details
            if hasattr(self, "details")
            else None
        )
        _links=(
            self.links
            if hasattr(self, "links")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"name={_name!r}, "
            f"message={_message!r}, "
            f"debug_id={_debug_id!r}, "
            f"details={_details!r}, "
            f"links={_links!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _name=self.name
        _message=self.message
        _debug_id=self.debug_id
        _details=(
            self.details
            if hasattr(self, "details")
            else None
        )
        _links=(
            self.links
            if hasattr(self, "links")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"name={_name!s}, "
            f"message={_message!s}, "
            f"debug_id={_debug_id!s}, "
            f"details={_details!s}, "
            f"links={_links!s}, "
            f")"
        )
